---
title: "Welcome to Zining Qi's website"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cerulean
---

## Resume
In this website, there is a resume page, which will introduce my personal information. This page includes my academic and professional experience. And this is the direct link to [Resume.](about.html) Or just click the **Resume** button on the top right corner.

## Email
Here is my [Email](mailto:<zq2209@cumc.columbia.edu>)(zq2209@cumc.columbia.edu).       
Or click on the envelop icon on the top right corner.

## Github Page
Here is my [Github Page.](https://github.com/zq2209/)    
Or click on the github icon on the top right corner.

## Instacart Dashboard
There is also a page for plots. These plots are made by using *instacart* dataset.    
The direct link is [here.](flexdashboard.html) Or click the **Dashboard** button on the up right corner.  


*Total numbers of items ordered in selected aisle (n > 15000):*    
This is the plot on the top right. Selected aisle are with more than 15000 ordered items. The y-axis shows the total number of items ordered. From left to right, the aisle are in ascending order along with total number of orders. It is easy to tell which aisle has the most ordered items, the two most popular aisle are fresh vegetables and packaged vegetables fruits.  
 
*Mean of days since last order for randomly selected products:*          
The plot on the left is the line plot of mean of days since last order for randomly selected products
The products set are randomly selected with size 30. This line plot can easily introduce the difference of days among 30 products. The product with small mean days of re-order means it is the most frequently re-ordered items, which is more necessary and popular for people.

*The hour in the day on which the order was placed of selected aisle:*           
The boxplot on the bottom right is the hour in the day on which the order was placed of selected aisle. It shows the distribution of order hour in some aisle. The information of mean, quantile and range can be easily pulled out from this plot. And it is convenient to compare distributions, mean, and range for these aisle.     





